name: Build and Deploy Service

on:
  workflow_dispatch:
    inputs:
      environment: 
        description: Environment to be run
        required: true
        type: choice 
        options:
          - Staging 
          - Production

jobs: 
  build-and-deploy:
    uses: xapo/pet-jenkins-to-gh-module/.github/workflows/build-and-deploy.yml@v1.0.3
    with:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    secrets: inherit